### ISSUE TITLE
The forward( ) and backward( ) about TopLeftPool

### ISSUE THREAD

**Issue by OliverHuang1220** [svip-lab/LBYLNet#6]
I have a question about  "TopLeftPool()", "TopRightPool()", "BottomLeftPool()", "BottomRightPool()".
The forward( ) is aim to get the max number for Dynamic Max Pooling,i think this step have updated the input,  but why also need a backward( ) function? This function update what?

**Comment by hbb1** [comment]
Hi Oliver, the backward function is for differentiation (that is calculating the gradient for back-propagation).
