### ISSUE TITLE
Does the pretrained visual backbone exclude val/test images on refcoco/+/g datasets ?

### ISSUE THREAD

**Issue by seanzhuh** [svip-lab/LBYLNet#7]
`wget -P ext https://pjreddie.com/media/files/yolov3.weights`

It seems that it actually does not exclude val/test images on refcoco/+/g datasets, this is unfair, since not removing val/test images during pretraining usually brings about 2-3 improments

**Comment by hbb1** [comment]
Thank you for your reminder. Yes, we haven't tried other pretrained backbone and this is somehow unfair compared to some two-stage methods. We may update the results using pretrained backbone exclude val/test images of refcoco series dataset. Actually, our setting follows one-stage methods like [**FAOA**](https://github.com/zyang-ur/onestage_grounding) and  [**ReSC**](https://github.com/zyang-ur/ReSC) with the same backbone.

**Comment by seanzhuh** [comment]
Thank you very much, still a great work. I'm wondering if you could kindly provide the ReferItGame dataset to me since the provided bash script can not download it, the link REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2" and REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz" is down. Could you send this dataset to my e-mail, which is sean.zhuh@gmail.com.

**Comment by hbb1** [comment]
I've uploaded the missing data here.
 https://pan.baidu.com/s/18KkE3dpkffEoK3QU85uPnA  
 Verification code: fi9c

**Comment by hbb1** [comment]
Solved. So I am closing this issue.  Please open more if other issues exist.
